#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: edu.xmu.autochessserver.entity
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/autochess?serverTimezone=GMT%2B8
    username: root
    password: 717496
    driver-class-name: com.mysql.cj.jdbc.Driver